spring:
  profiles:
    active: prod
  application:
    name: springboot-minio
  servlet:
    multipart:
      max-file-size: -1
server:
  port: 8085
minio:
  # 访问的url
  endpoint: http://localhost
  # API的端口
  port: 9001
  # 秘钥
  accessKey: OBD3o9tB4qZ9m24Q
  secretKey: iHqhpgrx3DSJ4atNtlqvFlh6rcJdOy04
  secure: false
  bucket-name: cyy # 桶名 我这是给出了一个默认桶名
  image-size: 10485760 # 我在这里设定了 图片文件的最大大小
  file-size: 1073741824 # 此处是设定了文件的最大大小
